using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.IO;
using System.Xml;
using System.Xml.Linq;
using System.Windows.Forms;
using System.Net;
using System.ComponentModel;
using System.IO.Compression;

namespace Undertale_Save_Manager_CE
{
    class USM
    {
        /* BEGIN GLOBAL VARIABLES */
        static public int version = 1;
        static public string DIR_APPDATA = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData);
        static public string DIR_LOCALAPPDATA = Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData);
        static public string DIR_UNDERTALE = DIR_LOCALAPPDATA + @"\UNDERTALE";
        static public string DIR_WORKINGDIRECTORY = DIR_APPDATA + @"\USMCE";
        static public string DIR_SAVES = DIR_WORKINGDIRECTORY + @"\Saves";
        static public string DIR_BACKUPS = DIR_WORKINGDIRECTORY + @"\Backups";
        static public string DIR_BIN = DIR_WORKINGDIRECTORY + @"\Bin";
        static public string DIR_CUSTOM_SAVES = Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments) + @"\USMCE Custom Saves\";
        static public string FILE_BACKUPSXML = DIR_BIN + @"\backups.xml";
        static public string FILE_SETTINGSXML = DIR_BIN + @"\settings.xml";
        static public string FILE_TEMPZIP = DIR_APPDATA + @"\temp.zip";
        static public string LINK_SAVEFILES = "https://www.dropbox.com/s/mqh5w1chfo79ymg/USMSaves.zip?dl=1";
        /* END GLOBAL VARIABLES */
        static public string getSetting(string setting)
        {
            XDocument doc = XDocument.Load(USM.FILE_SETTINGSXML);
            switch(setting)
            {
                default:
                    return "";
                case "CreateBackup":
                    return doc.Element("Settings").Element("CreateBackup").Value;
            }
        }
        static public void createDirs()//Function to create the needed directories
        {
            string[] dirs = new string[] {DIR_WORKINGDIRECTORY, DIR_BIN, DIR_SAVES, DIR_BACKUPS,DIR_CUSTOM_SAVES};
            foreach(string dir in dirs)
            {
                if(!Directory.Exists(dir))
                {
                    Directory.CreateDirectory(dir);
                }
            }
        }
        static public void createFiles() //Function to create the needed files
        {
            if(!File.Exists(FILE_BACKUPSXML))
            {
                XmlWriter writer = XmlWriter.Create(FILE_BACKUPSXML);
                writer.WriteComment("This file has been generated by Undertale Save Manager Community Edition. Edit at your own risk!");
                writer.WriteStartElement("Backups");
                writer.WriteEndElement();
                writer.Close();
            }
            if (!File.Exists(FILE_SETTINGSXML))
            {
                XmlWriter writer = XmlWriter.Create(FILE_SETTINGSXML);
                writer.WriteComment("This file has been generated by Undertale Save Manager Community Edition. Edit at your own risk!");
                writer.WriteStartElement("Settings");
                writer.WriteStartElement("CreateBackup");
                    writer.WriteString("true");
                writer.WriteEndElement();
                writer.WriteEndElement();
                writer.Close();
            }
        }
    }
}
